name: laptop_harbor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  image_picker: ^1.1.2 
  http: ^0.13.6
  file_picker: ^10.1.2


  firebase_storage: ^12.4.5
  provider: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
